---
title: "Resultados review fishing entities"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---
These are the results as January 12th 2017 on the review work. You must run "ReviewEEZ_FE_SP_list.R" first and then "Graphs Review".
```{r, echo=FALSE, warning=FALSE, error=FALSE}

library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)
ReviewDat <- read.csv("data/ReviewDat.csv", stringsAsFactors=FALSE)
FE_EEZ <- read.csv("data/FE_EEZ.csv", stringsAsFactors=FALSE)
#CATCH DEPENDENCY OF FISHING ENTITIES

#1. Species catch dependency on the area
ReviewDat$catchdepFEsp <- ReviewDat$tonnesFEsp/ReviewDat$tonnesFEspT #the dependence of the country species catches on the EEZ species catches
ReviewDat$landdepFEsp <-  ReviewDat$landedvalueFEsp/ReviewDat$landedvalueFEspT #the dependence of the country total SP Value on the EEZ SP catch value 
#2. Country dependency on the species in the area

ReviewDat$catchdepFE <- ReviewDat$tonnesFEsp/ReviewDat$tonnesFE #the dependence of the country species catches on the EEZ species catches
##VALUE OF SPECIES FOR FISHING ENTITIES

###Species VAlue in FE: landed value/tonnes

ReviewDat$spvalueFE  <- ReviewDat$landedvalueFEsp/ReviewDat$tonnesFEsp

##CATCH PRESSURE IN EEZ

ReviewDat$catchpresEEZsp <- ReviewDat$tonnesEEZsp/ReviewDat$tonnesEEZ
ReviewDat$landpresEEZsp <- ReviewDat$landedvalueEEZsp/ReviewDat$landedvalueEEZ

#prices in EEZs (something is wrong here, strange numbers!)
ReviewDat$spvalueEEZ <- ReviewDat$tonnesEEZsp/ReviewDat$landedvalueEEZsp 

##PREPARE VARIABLES FOR PLOTS

ReviewDat$b_value <- as.numeric(as.character(ReviewDat$b_value))
#Subsets of the impacts
ReviewDat$b_impact<-as.factor(ReviewDat$b_impact)
ReviewDat$b_value<-as.numeric(as.character(ReviewDat$b_value))

#levels(ReviewDatSAU$b_impact)
levels(ReviewDat$b_impact)<-c("mean lat shift", "mean lat shift", "depth shift", "boundary lat shift", "boundary lat shift", "mean long shift", "mean long shift", "mean lat and long shift", "area occupied")
#remove Nicolas (uds=6)
ReviewDat <- subset(ReviewDat, ReviewDat$id_study!=6)

latitude <- subset (ReviewDat, b_impact =="mean lat shift")
depth    <- subset (ReviewDat, b_impact=="depth shift")
range    <- subset (ReviewDat, b_impact== "boundary lat shift")
area     <- subset (ReviewDat, b_impact == "area occupied")
```

##Summary of the fishing activity for the Review Species
```{r , echo=FALSE, warning=FALSE, message=FALSE}

f1 <- ggplot(FE_EEZ, aes(x=fishing_entity, y=area_name))+
  geom_point(aes(size=tonnesFE_EEZ, colour=landedvalueFE_EEZ))+
  xlab("Fishing countries")+
  ylab("EEZ")+
  theme(axis.text.x = element_text(angle=-45, hjust= 0.06))+
  scale_color_gradient(low = "blue", high = "red")
f1
```

##Latitude Results

#Fishing entities
#Figure 1
```{r, echo=FALSE, warning=FALSE} 

#FE total catch dependency on species in EEZ


l1 <- ggplot(latitude, aes(catchdepFE, b_value, label = scientific_name)) +
  geom_jitter(alpha=0.8, aes(color=fishing_entity, size=tonnesFEsp),
              position = position_jitter(width = .001))+
  geom_text_repel(data=subset(latitude, latitude$catchdepFE>0.05), size=3, vjust=1)+
  geom_text_repel(data=subset(latitude, latitude$b_value>150), size=3, vjust=1)+
  ggtitle("Latitude Shift")+
  xlab("FE total catch dependency on species in EEZ")+
  ylab("km/decade")+
  theme(legend.position="bottom")
l1
```


#Figure 2
```{r, echo=FALSE, warning=FALSE} 

#FE species catch dependency in EEZ
l2 <- ggplot(latitude, aes(catchdepFEsp, b_value, label = scientific_name)) +
  #geom_point()
  geom_jitter(alpha=0.8, aes(color=fishing_entity, size=tonnesFEsp),
              position = position_jitter(width = .001))+
  geom_text_repel(data=subset(latitude, latitude$tonnesFEsp>100000), size=3, vjust=1)+
  geom_text_repel(data=subset(latitude, latitude$b_value>75), size=3, vjust=1)+
  ggtitle("FE species catch dependency in EEZ")+
  xlab("FE-SP catch dep")+
  ylab("km/decade")+
  ylim(-50, 100)+
  theme(legend.position="bottom")
  l2 
```

#Figure 3
```{r, echo=FALSE, warning=FALSE} 

##problema con los NAs?
l3 <- ggplot(latitude, aes(fishing_entity, b_value, label = scientific_name, na.rm=TRUE)) +
  #geom_point()
  geom_jitter(alpha=0.8, aes(color=catchdepFEsp, size=tonnesEEZsp),
              position = position_jitter(width = .001))+
  theme(axis.text.x = element_text(angle=-45, hjust= 0.06))+
  #geom_text_repel(data=subset(latitude, latitude$tonnesFEsp>20000), size=3, vjust=1)+
  ggtitle("impacts in fisheing entities")+
  xlab("FE-SP catch dep")+
  ylab("km/decade")
l3

```

#Figure 4
```{r, echo=FALSE, warning=FALSE} 

##using fishing entities in the X Axis

l4 <- ggplot(latitude, aes(fishing_entity,catchdepFE, label=scientific_name))+
  geom_point(aes(color=b_value, size=tonnesFEsp))+
  geom_text_repel(data=subset(latitude, latitude$catchdepFE>0.05), size=2, vjust=1)+
  theme(axis.text.x = element_text(angle=-45, hjust= 0.06))+
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Countries species dependence")
l4
```

#Figure 5
```{r, echo=FALSE, warning=FALSE} 
l5 <- ggplot(latitude, aes(fishing_entity,landedvalueFEsp, label=scientific_name))+
  geom_point(aes(color=b_value, size=tonnesFEsp))+
  geom_text_repel(data=subset(latitude, latitude$landedvalueFEsp>1e+08), size=2, vjust=1)+
  theme(axis.text.x = element_text(angle=-45, hjust= 0.06))+
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Countries species dependence - value")
l5
```



#Catch pressure in EEZs
#Figure 6
```{r, echo=FALSE, warning=FALSE} 


l6 <- ggplot(latitude, aes(catchpresEEZsp, b_value, label = scientific_name)) +
  #geom_point()
  geom_jitter(alpha=0.8, aes(color=area_name, size=tonnesEEZsp),
              position = position_jitter(width = .001))+
  geom_text_repel(data=subset(latitude, latitude$catchpresEEZsp>0.02), size=2, vjust=1)+
  geom_text_repel(data=subset(latitude, latitude$b_value>150), size=2, vjust=1)+  ggtitle("Latitude Shift")+
  xlab("EEZ-SP catch pressure")+
  ylab("km/decade")
l6 

```

#Figure 7
```{r, echo=FALSE, warning=FALSE} 

##using scientific names in the X Axis

l7 <- ggplot(latitude, aes(scientific_name,b_value, label=fishing_entity))+
  geom_point(aes(color=catchpresEEZsp, size=tonnesEEZ))+
  #geom_text_repel(data=subset(latitude, latitude$catchdepFE>0.05), size=3, vjust=1)+
  theme(axis.text.x = element_text(size=6, angle=-45, hjust= 0.06))+
  scale_color_gradient(low = "blue", high = "red")
l7

```

#Figure 8
```{r, echo=FALSE, warning=FALSE} 



l8 <- ggplot(latitude, aes(area_name,catchpresEEZsp, label=scientific_name))+
  geom_point(aes(color=b_value, size=tonnesEEZsp))+
  geom_text_repel(data=subset(latitude, latitude$catchpresEEZsp>0.01), size=2, vjust=1)+
  theme(axis.text.x = element_text(angle=-45, hjust= 0.06))+
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("EEZ species catch pressure")
l8

```

#Figure 9
```{r, echo=FALSE, warning=FALSE} 

l9 <- ggplot(latitude, aes(area_name,b_value, label=scientific_name))+
  geom_point(aes(color=catchpresEEZsp, size=tonnesEEZsp))+
  geom_text_repel(data=subset(latitude, latitude$catchpresEEZsp>0.01), size=2, vjust=1)+
  theme(axis.text.x = element_text(angle=-45, hjust= 0.06))+
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("EEZ species catch pressure")
l9


```
